### ISSUE TITLE
alt support

### ISSUE THREAD

**Issue by mattheww-freshview** [pexels/PexelsDotNetSDK#7]
Is there any plan to add `alt` (https://www.pexels.com/api/documentation/#photos-overview__response__alt) support to https://github.com/pexels/PexelsDotNetSDK/blob/d5f440c58af6f3088c50fc0a70543d9a4a074fa4/Models/Photo.cs ?

**Comment by squareballstudios** [comment]
This would also be of interest to us as well.

**Comment by gorgsenegger** [comment]
I added this in the [pull request](https://github.com/pexels/PexelsDotNetSDK/pull/9), but there doesn't seem to be too much activity in the repository recently - let's wait and see ;-)

**Comment by scgough** [comment]
Apologies for the delay! PR looks good 👍

**Comment by gorgsenegger** [comment]
Thanks for merging and no worries about the delay, we've all got other stuff to do in our lives ;-)
