### ISSUE TITLE
RateLimit.Reset is always 1970

### ISSUE THREAD

**Issue by mattheww-freshview** [pexels/PexelsDotNetSDK#8]
https://github.com/pexels/PexelsDotNetSDK/blob/9271072af1e5256447ee18ab34475da7c342f003/PexelsClient.cs#L352

I am 99% sure that ternary is the inverse of what it should be.

```
Reset = _resetValue != null ? start.AddMilliseconds(Convert.ToInt64(_resetValue)).ToLocalTime() : start.ToLocalTime()

// or alternatively
Reset = start.AddMilliseconds(Convert.ToInt64(_resetValue)).ToLocalTime()
```

Since, the _current_ code, as is, is effectively:

```
Reset = start.ToLocalTime()
```

since `Convert.ToInt64(null)` will evaluate to 0.

**Comment by scgough** [comment]
Agreed! Well spotted 😄 
I'll make the change to use `!=` 👍
